package board

const EMPTY_SQUARE = 0
const WHITE_PAWN = 1
const WHITE_KNIGHT = 2
const WHITE_BISHOP = 3
const WHITE_ROOK = 4
const WHITE_QUEEN = 5
const WHITE_KING = 6
const BLACK_PAWN = 7
const BLACK_KNIGHT = 8
const BLACK_BISHOP = 9
const BLACK_ROOK = 10
const BLACK_QUEEN = 11
const BLACK_KING = 12

type Board struct {
  pieces [64]int
  castle [2]bool
  ep *int
  // todo: 
  // repetition hash/counter 
  // fifty move rule
  // move history
  // move generation
}

var INIT_PIECES = [64]int{
  BLACK_ROOK,   BLACK_KNIGHT, BLACK_BISHOP, BLACK_QUEEN,  BLACK_KING,   BLACK_BISHOP, BLACK_KNIGHT, BLACK_ROOK,
  BLACK_PAWN,   BLACK_PAWN,   BLACK_PAWN,   BLACK_PAWN,   BLACK_PAWN,   BLACK_PAWN,   BLACK_PAWN,   BLACK_PAWN,
  EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE,
  EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE,
  EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE,
  EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE,
  WHITE_PAWN,   WHITE_PAWN,   WHITE_PAWN,   WHITE_PAWN,   WHITE_PAWN,   WHITE_PAWN,   WHITE_PAWN,   WHITE_PAWN,
  WHITE_ROOK,   WHITE_KNIGHT, WHITE_BISHOP, WHITE_QUEEN,  WHITE_KING,   WHITE_BISHOP, WHITE_KNIGHT, WHITE_ROOK,
}

var INIT_CASTLE = [2]bool{true, true}

func NewBoard() Board {
  return Board{
    INIT_PIECES,
    INIT_CASTLE,
    nil,
  }
}

