package board

const OFF_BOARD = -1
const EMPTY_SQUARE = 0
const WHITE_PAWN = 1
const WHITE_KNIGHT = 2
const WHITE_BISHOP = 3
const WHITE_ROOK = 4
const WHITE_QUEEN = 5
const WHITE_KING = 6
const BLACK_PAWN = 7
const BLACK_KNIGHT = 8
const BLACK_BISHOP = 9
const BLACK_ROOK = 10
const BLACK_QUEEN = 11
const BLACK_KING = 12

type Board struct {
	pieces [120]int
	castle [2]bool
	ep     *int
	// todo:
	// repetition hash/counter
	// fifty move rule
	// move history
	// move generation
}

var INIT_PIECES = [120]int{
	OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD,
	OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD,
	OFF_BOARD, BLACK_ROOK, BLACK_KNIGHT, BLACK_BISHOP, BLACK_QUEEN, BLACK_KING, BLACK_BISHOP, BLACK_KNIGHT, BLACK_ROOK, OFF_BOARD,
	OFF_BOARD, BLACK_PAWN, BLACK_PAWN, BLACK_PAWN, BLACK_PAWN, BLACK_PAWN, BLACK_PAWN, BLACK_PAWN, BLACK_PAWN, OFF_BOARD,
	OFF_BOARD, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, OFF_BOARD,
	OFF_BOARD, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, OFF_BOARD,
	OFF_BOARD, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, OFF_BOARD,
	OFF_BOARD, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, OFF_BOARD,
	OFF_BOARD, WHITE_PAWN, WHITE_PAWN, WHITE_PAWN, WHITE_PAWN, WHITE_PAWN, WHITE_PAWN, WHITE_PAWN, WHITE_PAWN, OFF_BOARD,
	OFF_BOARD, WHITE_ROOK, WHITE_KNIGHT, WHITE_BISHOP, WHITE_QUEEN, WHITE_KING, WHITE_BISHOP, WHITE_KNIGHT, WHITE_ROOK, OFF_BOARD,
	OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD,
	OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD,
}

var MAILBOX_64 = [64]int{
	21, 22, 23, 24, 25, 26, 27, 28,
	31, 32, 33, 34, 35, 36, 37, 38,
	41, 42, 43, 44, 45, 46, 47, 48,
	51, 52, 53, 54, 55, 56, 57, 58,
	61, 62, 63, 64, 65, 66, 67, 68,
	71, 72, 73, 74, 75, 76, 77, 78,
	81, 82, 83, 84, 85, 86, 87, 88,
	91, 92, 93, 94, 95, 96, 97, 98,
}

var INIT_CASTLE = [2]bool{true, true}

func NewBoard() Board {
	return Board{
		INIT_PIECES,
		INIT_CASTLE,
		nil,
	}
}

func (b Board) PieceAt(idx int) int {
	return b.pieces[MAILBOX_64[idx]]
}
