package board

const OFF_BOARD = -1
const EMPTY_SQUARE = 0
const WHITE_PAWN = 1
const WHITE_KNIGHT = 2
const WHITE_BISHOP = 3
const WHITE_ROOK = 4
const WHITE_QUEEN = 5
const WHITE_KING = 6
const BLACK_PAWN = 7
const BLACK_KNIGHT = 8
const BLACK_BISHOP = 9
const BLACK_ROOK = 10
const BLACK_QUEEN = 11
const BLACK_KING = 12

const WHITE = 0
const BLACK = 1

var INIT_PIECES = [120]int{
	OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD,
	OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD,
	OFF_BOARD, BLACK_ROOK, BLACK_KNIGHT, BLACK_BISHOP, BLACK_QUEEN, BLACK_KING, BLACK_BISHOP, BLACK_KNIGHT, BLACK_ROOK, OFF_BOARD,
	OFF_BOARD, BLACK_PAWN, BLACK_PAWN, BLACK_PAWN, BLACK_PAWN, BLACK_PAWN, BLACK_PAWN, BLACK_PAWN, BLACK_PAWN, OFF_BOARD,
	OFF_BOARD, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, OFF_BOARD,
	OFF_BOARD, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, OFF_BOARD,
	OFF_BOARD, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, OFF_BOARD,
	OFF_BOARD, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, OFF_BOARD,
	OFF_BOARD, WHITE_PAWN, WHITE_PAWN, WHITE_PAWN, WHITE_PAWN, WHITE_PAWN, WHITE_PAWN, WHITE_PAWN, WHITE_PAWN, OFF_BOARD,
	OFF_BOARD, WHITE_ROOK, WHITE_KNIGHT, WHITE_BISHOP, WHITE_QUEEN, WHITE_KING, WHITE_BISHOP, WHITE_KNIGHT, WHITE_ROOK, OFF_BOARD,
	OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD,
	OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD, OFF_BOARD,
}

var MAILBOX_64 = [64]int{
	21, 22, 23, 24, 25, 26, 27, 28,
	31, 32, 33, 34, 35, 36, 37, 38,
	41, 42, 43, 44, 45, 46, 47, 48,
	51, 52, 53, 54, 55, 56, 57, 58,
	61, 62, 63, 64, 65, 66, 67, 68,
	71, 72, 73, 74, 75, 76, 77, 78,
	81, 82, 83, 84, 85, 86, 87, 88,
	91, 92, 93, 94, 95, 96, 97, 98,
}

var INIT_CASTLE = [2]bool{true, true}

const (
	A8 = iota
	B8 = iota
	C8 = iota
	D8 = iota
	E8 = iota
	F8 = iota
	G8 = iota
	H8 = iota
	A7 = iota
	B7 = iota
	C7 = iota
	D7 = iota
	E7 = iota
	F7 = iota
	G7 = iota
	H7 = iota
	A6 = iota
	B6 = iota
	C6 = iota
	D6 = iota
	E6 = iota
	F6 = iota
	G6 = iota
	H6 = iota
	A5 = iota
	B5 = iota
	C5 = iota
	D5 = iota
	E5 = iota
	F5 = iota
	G5 = iota
	H5 = iota
	A4 = iota
	B4 = iota
	C4 = iota
	D4 = iota
	E4 = iota
	F4 = iota
	G4 = iota
	H4 = iota
	A3 = iota
	B3 = iota
	C3 = iota
	D3 = iota
	E3 = iota
	F3 = iota
	G3 = iota
	H3 = iota
	A2 = iota
	B2 = iota
	C2 = iota
	D2 = iota
	E2 = iota
	F2 = iota
	G2 = iota
	H2 = iota
	A1 = iota
	B1 = iota
	C1 = iota
	D1 = iota
	E1 = iota
	F1 = iota
	G1 = iota
	H1 = iota
)
